### ISSUE TITLE
Index columns labeled as continuous

### ISSUE THREAD

**Issue by amueller** [pvn25/ML-Data-Prep-Zoo#6]
There are some obvious index columns labeled as continuous. They should probably be labeled as not-generalizable, I think:

```python
train_merged[(train_merged.sample_1 == '0') & (train_merged.sample_2 == '1')  & (train_merged.sample_3 == '2')  & train_merged.total_vals == train_merged.num_of_dist_val].y_act.value_counts()
```
```
7    126
```

There's also a bunch of 1-based indices.

**Comment by vraj-ucsd** [comment]
I’m sorry I didn’t quite get you here. `7` is decoded as Not-Generalizable. So, the above command is returning 126 of Not-Gen. types. I will update the dataset to change the encoding to the actual feature types.

**Comment by amueller** [comment]
Hm, you're right, I'm not sure what I was after. I'm pretty sure I found some wrong labels, but this query doesn't show them.
